module.exports = class Data1730996568946 {
    name = 'Data1730996568946'

    async up(db) {
        await db.query(`CREATE TABLE "transfer" ("id" character varying NOT NULL, "from" text NOT NULL, "to" text NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "block_number" integer NOT NULL, "tx_hash" text NOT NULL, "log_index" integer NOT NULL, "block_hash" text NOT NULL, "asset_id" character varying, CONSTRAINT "PK_fd9ddbdd49a17afcbe014401295" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_e818cd083f48ed773afe017f7c" ON "transfer" ("asset_id") `)
        await db.query(`CREATE INDEX "IDX_f605a03972b4f28db27a0ee70d" ON "transfer" ("tx_hash") `)
        await db.query(`CREATE TABLE "asset" ("id" character varying NOT NULL, "token_id" text NOT NULL, "owner" text NOT NULL, "ownership_contract_id" character varying, CONSTRAINT "PK_1209d107fe21482beaea51b745e" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_dc1699251752ca3b19442d8800" ON "asset" ("ownership_contract_id") `)
        await db.query(`CREATE TABLE "ownership_contract" ("id" character varying NOT NULL, "laos_contract" text, CONSTRAINT "PK_6ef3226ceefbd82ad30b9075bdf" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_940175c34e4f87552f002f428a" ON "ownership_contract" ("laos_contract") `)
        await db.query(`CREATE TABLE "laos_asset" ("id" character varying NOT NULL, "laos_contract" text NOT NULL, "token_id" text NOT NULL, "initial_owner" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "log_index" integer NOT NULL, "metadata" text, CONSTRAINT "PK_b922ae1a317644c470a64c7174f" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_ff8a3b3470ab42f6d7d20f9d84" ON "laos_asset" ("laos_contract") `)
        await db.query(`CREATE INDEX "IDX_e4e4978a0c9d154a00e1ad3830" ON "laos_asset" ("metadata") `)
        await db.query(`CREATE TABLE "token_uri" ("id" character varying NOT NULL, "state" text NOT NULL, "name" text, "description" text, "image" text, "attributes" jsonb, "fetched" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_1f5797cb07d9a79407a00292363" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "metadata" ("id" character varying NOT NULL, "block_number" integer NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "tx_hash" text NOT NULL, "laos_asset_id" character varying, "token_uri_id" character varying, CONSTRAINT "PK_56b22355e89941b9792c04ab176" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_90484e3241344e9b970c82ea67" ON "metadata" ("laos_asset_id") `)
        await db.query(`CREATE INDEX "IDX_d14ff181d0e754aba6f171d59b" ON "metadata" ("token_uri_id") `)
        await db.query(`CREATE INDEX "IDX_78be4c41c64f3ec6913882574b" ON "metadata" ("tx_hash") `)
        await db.query(`CREATE TABLE "attack" ("id" character varying NOT NULL, "token_ids" text array NOT NULL, "target_address" text NOT NULL, "operator" text NOT NULL, "attacker" text NOT NULL, "target_chain" integer NOT NULL, "strategy" integer NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "block_number" integer NOT NULL, "block_hash" text NOT NULL, "tx_hash" text NOT NULL, "log_index" integer NOT NULL, CONSTRAINT "PK_b63e4c74e7b45ef2d42a82bdabc" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_d54120e053317a8c4a23d8fad6" ON "attack" ("tx_hash") `)
        await db.query(`CREATE TABLE "chain_action_proposal" ("id" character varying NOT NULL, "operator" text NOT NULL, "user" text NOT NULL, "source_chain" integer NOT NULL, "target_chain" integer NOT NULL, "action_type" integer NOT NULL, "attack_area" integer NOT NULL, "attack_address" text NOT NULL, "comment" text NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "block_number" integer NOT NULL, "block_hash" text NOT NULL, "tx_hash" text NOT NULL, "log_index" integer NOT NULL, CONSTRAINT "PK_74a8d749859e931b0349e281839" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_faa4bf8cd98a4ed4c8e4b9125c" ON "chain_action_proposal" ("tx_hash") `)
        await db.query(`CREATE TABLE "joined_chain" ("id" character varying NOT NULL, "user" text NOT NULL, "home_chain" integer NOT NULL, "nickname" text NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "block_number" integer NOT NULL, "block_hash" text NOT NULL, "tx_hash" text NOT NULL, "log_index" integer NOT NULL, CONSTRAINT "PK_30b23a88aa83d1257ec40f9ffec" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_051e69cc6a3fb31392c6203b8f" ON "joined_chain" ("tx_hash") `)
        await db.query(`CREATE TABLE "multichain_mint" ("id" character varying NOT NULL, "token_id" text NOT NULL, "user" text NOT NULL, "type_id" text NOT NULL, "home_chain" integer NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "block_number" integer NOT NULL, "block_hash" text NOT NULL, "tx_hash" text NOT NULL, "log_index" integer NOT NULL, CONSTRAINT "PK_d1094080b8874215a9fc80c9d74" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_fb3cdba7d46e0a5642c5f62254" ON "multichain_mint" ("tx_hash") `)
        await db.query(`CREATE TABLE "upgrade" ("id" character varying NOT NULL, "operator" text NOT NULL, "user" text NOT NULL, "chain" integer NOT NULL, "token_id" text NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "block_number" integer NOT NULL, "block_hash" text NOT NULL, "tx_hash" text NOT NULL, "log_index" integer NOT NULL, CONSTRAINT "PK_855aca5df3eceff6e4fe49245c4" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_1ad5927f3c2939ee4875a26a5b" ON "upgrade" ("tx_hash") `)
        await db.query(`CREATE TABLE "send_game_treasury" ("id" character varying NOT NULL, "from" text NOT NULL, "method" integer NOT NULL, "send_t_xs" jsonb NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "block_number" integer NOT NULL, "block_hash" text NOT NULL, "tx_hash" text NOT NULL, "log_index" integer NOT NULL, CONSTRAINT "PK_5022a0f222d1cfa30cf4d764c23" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_010d3131085434f97ea24d7d4c" ON "send_game_treasury" ("tx_hash") `)
        await db.query(`CREATE TABLE "assign_operator" ("id" character varying NOT NULL, "from" text NOT NULL, "operator" text NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "block_number" integer NOT NULL, "block_hash" text NOT NULL, "tx_hash" text NOT NULL, "log_index" integer NOT NULL, CONSTRAINT "PK_29da423f6515dc686dcc301d726" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_0b7fa9d6593eb62cecfb42af39" ON "assign_operator" ("tx_hash") `)
        await db.query(`CREATE TABLE "register_mercenary" ("id" character varying NOT NULL, "mercenary_address" text NOT NULL, "mercenary_chain" integer NOT NULL, "mercenary_nickname" text NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "block_number" integer NOT NULL, "block_hash" text NOT NULL, "tx_hash" text NOT NULL, "log_index" integer NOT NULL, CONSTRAINT "PK_0f5540b9ede3cdf8b6468152a63" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_ee63cf0b4465a10b3151a3b126" ON "register_mercenary" ("tx_hash") `)
        await db.query(`ALTER TABLE "transfer" ADD CONSTRAINT "FK_e818cd083f48ed773afe017f7c0" FOREIGN KEY ("asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "asset" ADD CONSTRAINT "FK_dc1699251752ca3b19442d8800e" FOREIGN KEY ("ownership_contract_id") REFERENCES "ownership_contract"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "metadata" ADD CONSTRAINT "FK_90484e3241344e9b970c82ea67d" FOREIGN KEY ("laos_asset_id") REFERENCES "laos_asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "metadata" ADD CONSTRAINT "FK_d14ff181d0e754aba6f171d59bc" FOREIGN KEY ("token_uri_id") REFERENCES "token_uri"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`DROP TABLE "transfer"`)
        await db.query(`DROP INDEX "public"."IDX_e818cd083f48ed773afe017f7c"`)
        await db.query(`DROP INDEX "public"."IDX_f605a03972b4f28db27a0ee70d"`)
        await db.query(`DROP TABLE "asset"`)
        await db.query(`DROP INDEX "public"."IDX_dc1699251752ca3b19442d8800"`)
        await db.query(`DROP TABLE "ownership_contract"`)
        await db.query(`DROP INDEX "public"."IDX_940175c34e4f87552f002f428a"`)
        await db.query(`DROP TABLE "laos_asset"`)
        await db.query(`DROP INDEX "public"."IDX_ff8a3b3470ab42f6d7d20f9d84"`)
        await db.query(`DROP INDEX "public"."IDX_e4e4978a0c9d154a00e1ad3830"`)
        await db.query(`DROP TABLE "token_uri"`)
        await db.query(`DROP TABLE "metadata"`)
        await db.query(`DROP INDEX "public"."IDX_90484e3241344e9b970c82ea67"`)
        await db.query(`DROP INDEX "public"."IDX_d14ff181d0e754aba6f171d59b"`)
        await db.query(`DROP INDEX "public"."IDX_78be4c41c64f3ec6913882574b"`)
        await db.query(`DROP TABLE "attack"`)
        await db.query(`DROP INDEX "public"."IDX_d54120e053317a8c4a23d8fad6"`)
        await db.query(`DROP TABLE "chain_action_proposal"`)
        await db.query(`DROP INDEX "public"."IDX_faa4bf8cd98a4ed4c8e4b9125c"`)
        await db.query(`DROP TABLE "joined_chain"`)
        await db.query(`DROP INDEX "public"."IDX_051e69cc6a3fb31392c6203b8f"`)
        await db.query(`DROP TABLE "multichain_mint"`)
        await db.query(`DROP INDEX "public"."IDX_fb3cdba7d46e0a5642c5f62254"`)
        await db.query(`DROP TABLE "upgrade"`)
        await db.query(`DROP INDEX "public"."IDX_1ad5927f3c2939ee4875a26a5b"`)
        await db.query(`DROP TABLE "send_game_treasury"`)
        await db.query(`DROP INDEX "public"."IDX_010d3131085434f97ea24d7d4c"`)
        await db.query(`DROP TABLE "assign_operator"`)
        await db.query(`DROP INDEX "public"."IDX_0b7fa9d6593eb62cecfb42af39"`)
        await db.query(`DROP TABLE "register_mercenary"`)
        await db.query(`DROP INDEX "public"."IDX_ee63cf0b4465a10b3151a3b126"`)
        await db.query(`ALTER TABLE "transfer" DROP CONSTRAINT "FK_e818cd083f48ed773afe017f7c0"`)
        await db.query(`ALTER TABLE "asset" DROP CONSTRAINT "FK_dc1699251752ca3b19442d8800e"`)
        await db.query(`ALTER TABLE "metadata" DROP CONSTRAINT "FK_90484e3241344e9b970c82ea67d"`)
        await db.query(`ALTER TABLE "metadata" DROP CONSTRAINT "FK_d14ff181d0e754aba6f171d59bc"`)
    }
}
