contractAddress: 0x6B6F742352A92A301E2B4F6247403CF088Ec4da3
walletConnectProjectId: 83269252958e4da258ce79fa451ce3fe
bocApiUrl: https://boc.api.gorengine.com/graphql
uiHost: boc.gorengine.com
namespace: battle-of-chains