export const tooltips = {
  userInformation: "Homechain: the chain you support, which allows you to vote for its Chain Daily Actions.\nScore: your overall score, earned through different actions in the game",
  userActivity: "All events related to you: your mints, attacks, and upgrades,\nother players planning to attack you, etc.",
  homeBase: "Your Home Base generates treasury resources constantly.\nUpgrade: attempts to level up your home base to increase its production rate; the upgrade will not be applied unless you have enough balance in your treasury.\nXP: your current experience points.\nXP Needed for Next Level: the amount of XP at which your next level increase will happen.\nDaily Production Rate: the amount added to your treasury over 24 hours, given your current level.\nCost of one XP: the treasury amount required per XP increased",
  inventory: "The assets you own across different chains.\nAttack/Defend Factories of higher levels allow you to mint better attack/defend assets.\nYou can upgrade factories or individual assets.\nWhen minting an attack/defend asset, the resulting level will depend on the level of the best factory you own in the corresponding chain,\nand on whether you have enough treasury to mint assets of that level.\nAll your assets can be traded on the corresponding chains",
  players: "All players in the game.\nClick on View Details to view their assets and initiate attacks",
  universeSummary: "Chronological log of all activities across all chains, including attacks, upgrades, and chain actions.\nThe Player column specifies the target of a log.\nThe Chain column specifies the Chain Daily Actions",
  chainDailyDecision: "Vote on your homechain Daily Action, which happens daily at 2 PM UTC.\nVotes are weighted by each voter's treasury and reset after execution of the action.\n'Improve' will increase XP and health of all assets in your homechain.\n'Defend' will significantly reduce potential attacks by other chains.\n'Attack' will inflict damage on an entire chain, part of it, or one single address on it.\nLeave a comment on-chain for others to support you.",
  chainActionProposals: "All current proposals across different chains and their total vote counts.\nVotes are weighted by each voter's treasury and reset after execution of the action",
  map: "All players' coordinates along with their respective home bases and outposts in any chain.",
  chainLeaderboard: "Leaderboard displaying the top chains in the game.\nA chain's score is the total of the scores of users who have that chain as their homechain.",
  userLeaderboard: "Leaderboard displaying the top users in the game",
};
