repositories:
  - name: stable
    url: https://charts.helm.sh/stable


environments:
  default:
    values:
      - ./environments/values.dev.yaml
  development:
    values:
      - ./environments/values.dev.yaml

helmfiles:
  - path: 'charts/ui/helmfile.yaml'
    values:
      - namespace: {{ .Values.namespace }}
      - walletConnectProjectId: {{ .Values.walletConnectProjectId }}
      - bocApiUrl: {{ .Values.bocApiUrl }}
      - contractAddress: {{ .Values.contractAddress }}
      - imageTag: {{ requiredEnv "CIRCLE_SHA1" }}
      - uiHost: {{ .Values.uiHost }}


