apiVersion: apps/v1
kind: Deployment
metadata:
  name: boc-ui
  labels:
    app.kubernetes.io/app: boc-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/app: boc-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/app: boc-ui
    spec:
      containers:
        - name: boc-ui
          image: freeverseio/battle-of-chains-ui:{{ .Values.imageTag }}
          resources:
            requests:
              memory: '256Mi'
              cpu: '125m'
            limits:
              memory: '512Mi'
              cpu: '1'
          imagePullPolicy: Always
          env:
            - name: NEXT_PUBLIC_LAOS_CONTRACT_ADDRESS
              value: {{ .Values.contractAddress }}
            - name: NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID
              value: {{ .Values.walletConnectProjectId }}
            - name: NEXT_PUBLIC_BOC_API_URL
              value: {{ .Values.bocApiUrl }}
      imagePullSecrets:
        - name: docker-secret
