type Attribute {
    traitType: String!
    value: String!
}
type OwnershipContract @entity {
  id: ID!
  laosContract: String  @index
}

type Attack @entity {
  id: ID!
  tokenIds: [String!]!
  targetAddress: String!
  operator: String!
  attacker: String!
  targetChain: Int!
  strategy: Int!
  timestamp: DateTime!
  blockNumber: Int!
  blockHash: String!
  txHash: String! @index
  logIndex: Int!
}

type ChainActionProposal @entity {
  id: ID!
  operator: String!
  user: String!
  sourceChain: Int!
  targetChain: Int!
  actionType: Int!
  attackArea: Int!
  attackAddress: String!
  comment: String!
  timestamp: DateTime!
  blockNumber: Int!
  blockHash: String!
  txHash: String! @index
  logIndex: Int!
}

type JoinedChain @entity {
  id: ID!
  user: String!
  homeChain: Int!
  nickname: String!
  timestamp: DateTime!
  blockNumber: Int!
  blockHash: String!
  txHash: String! @index
  logIndex: Int!
}

type MultichainMint @entity {
  id: ID!
  tokenId: String!
  user: String!
  typeId: String!
  homeChain: Int!
  timestamp: DateTime!
  blockNumber: Int!
  blockHash: String!
  txHash: String! @index
  logIndex: Int!
}

type Upgrade @entity {
  id: ID!
  operator: String!
  user: String!
  chain: Int!
  tokenId: String!
  timestamp: DateTime!
  blockNumber: Int!
  blockHash: String!
  txHash: String! @index
  logIndex: Int!
}

type SendTX {
  recipient: String!
  amount: String!
}

type SendGameTreasury @entity {
  id: ID!
  from: String!
  method: Int!
  sendTXs: [SendTX!]!
  timestamp: DateTime!
  blockNumber: Int!
  blockHash: String!
  txHash: String! @index
  logIndex: Int!
}

type AssignOperator @entity {
  id: ID!
  from: String!
  operator: String!
  timestamp: DateTime!
  blockNumber: Int!
  blockHash: String!
  txHash: String! @index
  logIndex: Int!
}

type RegisterMercenary @entity {
  id: ID!
  operator: String!
  mercenaryAddress: String!
  mercenaryChain: Int!
  mercenaryNickname: String!
  timestamp: DateTime!
  blockNumber: Int!
  blockHash: String!
  txHash: String! @index
  logIndex: Int!
}